### ISSUE TITLE
Warning (emacs): Please update your org protocol handler to deal with new-style links.

### ISSUE THREAD

**Issue by lengyueyang** [alphapapa/org-protocol-capture-html#14]
Thanks very much for this package, when I use this package, the warning appeared, I use the latest org edition, so I don't know why ?
```
Warning (emacs): Please update your org protocol handler to deal with new-style links.
```

**Comment by alphapapa** [comment]
Hi there,

Yeah, I noticed in the Org 9 changelog that the org-protocol URL syntax changed.  It's definitely an improvement, but I guess we'll have to check `org-version` and handle the change appropriately.  There will probably be people still using Org 8 for years to come.  

Thanks for reporting.  I'll try to get to it in a few weeks, a bit busy right now...  :)

By the way, it still works despite the warning in the minibuffer, right?  Just making sure.

**Comment by lengyueyang** [comment]
Yes, it still works despite the warning in the minibuffer, thanks.

**Comment by Gahamelas** [comment]
I keep getting this warning. Is there a way to remove it or update the syntax?
