### ISSUE TITLE
"Symbol’s function definition is void: remove-dos-crlf"

### ISSUE THREAD

**Issue by xuchunyang** [alphapapa/org-protocol-capture-html#16]
When I use `org-protocol://capture-eww-readable`, Emacs fails by reporting

> Symbol’s function definition is void: remove-dos-crlf

I search github for `remove-dos-crlf` and it occurs only in this repo.

**Comment by alphapapa** [comment]
Sorry about that, I added that function from my personal config, and I didn't realize it called another function from my personal config.  Thank you for reporting!
