### ISSUE TITLE
*ERROR*: Invalid file location: ""

### ISSUE THREAD

**Issue by ouboub** [alphapapa/org-protocol-capture-html#23]
Hi 

I am using Kubuntu 14.04 and GNU emacs 26 (pandoc 1.19)
I compiled and installed the lisp file, then I run 
org-protocol-capture-html.sh --readability --url "https://github.com/alphapapa/org-protocol-capture-html"

and obtain 

Waiting for Emacs...
*ERROR*: Invalid file location: ""

what is wrong?

**Comment by alphapapa** [comment]
I don't know.  Enable `debug-on-error` and see what the backtrace shows.

**Comment by ouboub** [comment]
set debug-on-error to t, but no error message poped up. I use your template
("w" "Web site" entry
  (file (lambda () ""))
  "* %a :website:\n\n%U %?\n\n%:initial")
oops this is the wrong template so I tried
("w" "Web site" entry
  (file "")
  "* %a :website:\n\n%U %?\n\n%:initial")
now I obtain 
*ERROR*: Capture template ‘w’: Template is not a valid Org entry or tree

But I found out about org-web-tools, this is also your brainchild, isn't it. that works as expected save the annoying translation from pandoc for some html pages

However I found

**Comment by alphapapa** [comment]
You're not specifying the capture template correctly.  `file` needs to be followed by the path to a file.  See the help for `org-capture-templates`.

**Comment by ouboub** [comment]
oops sorry you are right so I changed thetemplace to  to 
("w" "Web site" entry
  (file "/home/oub/ALLES/download.org")
  "* %a :website:\n\n%U %?\n\n%:initial")
but now emacsclient pops up with an empty buffer

**Comment by alphapapa** [comment]
Did you configure org-protocol according to the instructions?

**Comment by alphapapa** [comment]
I'm going to close this since I don't think it's a bug.  If you still can't get it working, reply here or on the org-mode mailing list.

**Comment by AtomicNess123** [comment]
If the path is to a folder, not exactly a file, what should be the syntax?
