### ISSUE TITLE
Can we use this for turning links into org format ?

### ISSUE THREAD

**Issue by azzamsa** [alphapapa/org-protocol-capture-html#25]
I use org-mode all the time for various documentation. copy-paste links all the time from web to org-mode buffer. [Copy as org-mode](https://github.com/kuanyui/copy-as-org-mode) helped me a lot, but now it does not support Firefox Quantum.

Can we use org-protocol-capture-html to take web title and turn it into org-mode link format ?

e.g from [this](https://stackoverflow.com/questions/6429638/how-to-split-a-string-into-integers-in-python) page the title we can copy " How to split a string into integers in Python? ", and become valid org link format `[[https://stackoverflow.com/questions/6429638/how-to-split-a-string-into-integers-in-python][ How to split a string into integers in Python?]]`

Thank you.

**Comment by alphapapa** [comment]
Yes.

**Comment by azzamsa** [comment]
Thank you.
But I think this project is overkill just for my simple need. so I took another approach.

I use copy-as-markdown to my org-mode buffer than invoke [my function](https://github.com/azzamsa/emacs.d/blob/master/myelisp/make-md-to-org.el) to transform the link to org-mode.
