### ISSUE TITLE
Pandoc 1.16 deprecates --no-wrap

### ISSUE THREAD

**Issue by cryoguy** [alphapapa/org-protocol-capture-html#3]
I can only capture url not content with following message under：　 pandoc: --no-wrap is deprecated. Use --wrap=none or --wrap=preserve instead.　　any thoughts?  Thanks.

**Comment by alphapapa** [comment]
Hi,

Sorry, GitHub isn't showing notifications for my own repos at the top of my notification list, so I didn't notice your report.

Here's what I have from the Pandoc 1.12.2.1 man page:

```
--no-wrap
              Disable text wrapping in output.  By default, text is wrapped appropriately for the output format.
```

I don't even see a `--wrap` option.  What version of Pandoc do you have?  I'm guessing it's a newer one than I have installed.  It should be a fairly easy fix if that's the case, we just need to find out what version of Pandoc is the minimum for using `--wrap`.

Thanks.

**Comment by alphapapa** [comment]
Have you had any luck in figuring this out?  Ping.  :)

**Comment by raamdev** [comment]
@alphapapa I can confirm that the [newer-pandoc](https://github.com/alphapapa/org-protocol-capture-html/tree/newer-pandoc) branch fixes the issue.

I'm using `pandoc 1.17.0.3` and after select and clip the content of an HTML page, I was seeing the following appear in Emacs:

```
* [[URL[TITLE]]

[DATE] 

pandoc: --no-wrap is deprecated. Use --wrap=none or --wrap=preserve instead.
CLIPPED CONTENT
```

Notice that `pandoc: --no-wrap is deprecated.` line that seems out of place? That was being injected into the buffer above the body of my clipped content.

When I retested with the [newer-pandoc](https://github.com/alphapapa/org-protocol-capture-html/tree/newer-pandoc) branch, out of place deprecated notice no longer appeared in Emacs. :-)

**Comment by alphapapa** [comment]
@raamdev Thanks.  The problem is that earlier versions of Pandoc, like 1.12.2.1 in Ubuntu Trusty, don't have the `--wrap` option at all.  Seems like a bit of a botched deprecation by Pandoc.  That deprecation warning should go to STDERR not STDOUT.  Grr.

**Comment by Georgiy-Tugai** [comment]
> `call-process-region` seems to only allow you to discard it, mix it with STDOUT, or put it in a file, while the most useful would be to put it in a buffer. Sigh.

The answer seems obvious to me -- toss it into a temporary file, and open that file in a buffer.

Alternatively, on the first call, detect pandoc version by trying to use `--wrap` option and checking the error code.

**Comment by alphapapa** [comment]
This should fix it by testing Pandoc to see which option it supports.  Please test the current master and let me know if there are any problems.  Sorry it took me so long.  :)

**Comment by Georgiy-Tugai** [comment]
Works OK, thanks!
