### ISSUE TITLE
Emacs sometimes freezes after using capture

### ISSUE THREAD

**Issue by jtrakk** [alphapapa/org-protocol-capture-html#35]
Often after I use the snippet a few times, Emacs will lock up and stop responding to keypresses, and I have to `kill` emacs. I don't know why this would be, but I'm pretty confident that it only happens after I use this plugin. I use this plugin very often, so it can be a bit inconvenient :-). 

I realize this isn't much of a report, but I don't have any ideas for narrowing it down. I'm posting this mostly in case somebody has seen something similar and solved it.

I'm interested in any thoughts anybody has. :-)

org-protocol-capture-html `94c110c`
GNU Emacs 26.1 
Ubuntu 18.04

**Comment by alphapapa** [comment]
Like you said, there's not much I can do with that report, but anyway:

> org-protocol-capture-html 94c110c

There's no commit with that hash in this repo.

> GNU Emacs 26.1

That's not the current version of Emacs.

> Often after I use the snippet a few times, Emacs will lock up and stop responding to keypresses, and I have to kill emacs.

1.  See if there's an `emacsclient` process running when Emacs appears to be frozen.
2.  You almost never have to actually kill Emacs.  Try `pkill -SIGUSR2 emacs`, which should unfreeze it and display a backtrace.

**Comment by jtrakk** [comment]
Thanks for the tips, I'll try them out next time this happens.

**Comment by jtrakk** [comment]
I'm now on Emacs 26.2 and org-protocol-capture-html version `23a1336`. It stops responding to keyboard input, while still accepting mouse input. When I send `SIGUSR2`, the debugger shows `company-pre-command`, but it still doesn't accept keyboard input. Killing emacs solves the issue. 

I'm gonna close the issue for now. If you have any ideas, I'd be interested to hear. Thanks :-)

**Comment by alphapapa** [comment]
Sounds like the problem is related to `company-pre-command`.  Try removing `company`-related things from your config.
