### ISSUE TITLE
It seems to stop working on Emacs 28.0.5 and org-mode 9.3.

### ISSUE THREAD

**Issue by tlkahn** [alphapapa/org-protocol-capture-html#40]
I keep running into this error:

```
Greedy org-protocol handler.  Killing client.
No server buffers remain to edit
```
org-capture-templates are set up and used to run properly:
```
(setq org-capture-templates
      (quote
       (
        ;; ("w"
        ;;  "Default template"
        ;;  entry
        ;;  (file+headline "~/org/capture.org" "Notes")
        ;;  "* %^{Title}\n\n  Source: %u, %c\n\n  %i"
        ;;  :empty-lines 1)
        ;; ... more templates here ...
        ;; ("w" "Web site" entry
        ;;  (file "")
        ;;  "* %a :website:\n\n%U %?\n\n%:initial")
				("w" "Web site" entry
				 (file "")
				 "* %a :website:\n\n%U %?\n\n%:initial")
        ("t" "todo" entry (file org-default-notes-file)
         "* TODO %?\n%u\n%a\n" :clock-in t :clock-resume t)
        ("m" "Meeting" entry (file org-default-notes-file)
         "* MEETING with %? :MEETING:\n%t" :clock-in t :clock-resume t)
        ("d" "Diary" entry (file "~/org/diary.org")
         "* %?\n%U\n" :clock-in t :clock-resume t)
        ("i" "Idea" entry (file org-default-notes-file)
         "* %? :IDEA: \n%t" :clock-in t :clock-resume t)
        ("n" "Next Task" entry (file org-default-notes-file "Tasks")
         "** NEXT %? \nDEADLINE: %t"
         )
        ;; ("p" "Protocol" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
        ;; "* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?")
	;; ("L" "Protocol Link" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
        ;; "* %? [[%:link][%:description]] \nCaptured On: %U")
        ;; ("l" "Protocol Link" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
        ;;  "* %? [[%:link][%:description]] \nCaptured On: %U")
        ("p" "Protocol Link" entry
         (file "")
         "* %a :website:\n\n%U %?\n\n%:initial")
        ("L" "Protocol Link" entry
         (file "")
         "* %a :website:\n\n%U %?\n\n%:initial")
        )))
```

**Comment by tlkahn** [comment]
When I update the bookmark on Chrome to:
'''
javascript:location.href = 'org-protocol:///capture-html://w/' + encodeURIComponent(location.href) + '/' + encodeURIComponent(document.title || "[untitled page]") + '/' + encodeURIComponent(function () {var html = ""; if (typeof window.getSelection != "undefined") {var sel = window.getSelection(); if (sel.rangeCount) {var container = document.createElement("div"); for (var i = 0, len = sel.rangeCount; i < len; ++i) {container.appendChild(sel.getRangeAt(i).cloneContents());} html = container.innerHTML;}} else if (typeof document.selection != "undefined") {if (document.selection.type == "Text") {html = document.selection.createRange().htmlText;}} var relToAbs = function (href) {var a = document.createElement("a"); a.href = href; var abs = a.protocol + "//" + a.host + a.pathname + a.search + a.hash; a.remove(); return abs;}; var elementTypes = [['a', 'href'], ['img', 'src']]; var div = document.createElement('div'); div.innerHTML = html; elementTypes.map(function(elementType) {var elements = div.getElementsByTagName(elementType[0]); for (var i = 0; i < elements.length; i++) {elements[i].setAttribute(elementType[1], relToAbs(elements[i].getAttribute(elementType[1])));}}); return div.innerHTML;}());
'''
Emacs popup a warning:
```
Warning (emacs): Please update your Org Protocol handler to deal with new-style links.
```

**Comment by alphapapa** [comment]
In years past I encountered that error now and then.  You might find some issues mentioning it here.

Unless you can show that it happens due to a change in Emacs or Org, and that this package needs to be updated accordingly, I'm afraid I can't help you with it.

**Comment by tlkahn** [comment]
I still cannot figure out the cause... Close the issue for now.
