### ISSUE TITLE
How to close each generated Emacs window

### ISSUE THREAD

**Issue by AtomicNess123** [alphapapa/org-protocol-capture-html#47]
New question: how to close each opened window after invoking org-protocol? Thanks!

**Comment by alphapapa** [comment]
I don't know exactly what you're asking, but it would probably be best to ask in a more appropriate forum, like Reddit, IRC, or a mailing list.  Thanks.

**Comment by AtomicNess123** [comment]
I meant that frames (not windows) are created every time org protocol is called, and how to avoid them.

**Comment by alphapapa** [comment]
AFAIK that issue is orthogonal to the code in this package.  Please ask in a suitable place where other users can offer help.
